name: spleeter
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ffmpeg              
  - libsndfile          
  - numpy<1.24.0     
  - pandas<2.2.0    
  - scipy               
  - tensorboard
  - typer
  - click
  - huggingface_hub<1.0
  - pip
  - pip:
    - spleeter==2.4.0
    - hf_transfer
    - mir_eval
    - musdb
    - stempeg
    - soundfile
    - librosa
    - httpx[http2]